repos:
  - repo: https://github.com/PyCQA/isort
    rev: c655831799765e9593989ee12faba13b6ca391a5  # 5.13.2
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: 6fdf8a4af28071ed1d079c01122b34c5d587207a  # 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 88a4f9b2f48fc44b025a48fa6a8ac7cc89ef70e0  # 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # v4.5.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-docstring-first
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 8cd2d4056637e242709fe09f15a36f0b4b682bda  # v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
