name: Code Quality

on: pull_request

jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # @v4.1.1
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # @v5.0.0
      with:
        python-version: '3.9'
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # @v3.0.1
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # @v4.1.1
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # @v5.0.0
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Test with pytest
      run: |
        pytest
